import type { TutorialStep } from './types';

export const DATA_OVERLAY_TUTORIAL_ID = 'data-overlay' as const;

export const DATA_TUTORIAL_RESET_OVERRIDE_IDS = [
  'product:p_coal',
  'product:p_cat',
  'product:p_coal_ingot',
  'machine:m_coal_drill',
  'machine:m_blast_furnace',
  'machine:m_coal_ingot_factory',
  'recipe:r_coal_drill_01',
  'recipe:r_coal_ingot_factory_01',
];

export const DATA_OVERLAY_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'intro',
    title: 'Data Manager',
    description:
      'Data Manager lets you edit products, machines, recipes, and research data, then compare app data against external wiki buckets.',
    highlight: { kind: 'overlay', id: 'data' },
    action: { type: 'continue' },
  },
  {
    id: 'open-data',
    title: 'Open Data Manager',
    description: 'Open the Data Manager overlay.',
    highlight: { kind: 'overlay', id: 'data' },
    action: { type: 'overlay', id: 'data' },
  },
  {
    id: 'parts',
    title: 'Editing And Comparing',
    description:
      'Editing changes the app database. Comparing checks local records against fetched wiki data so you can spot differences.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-main-tab="editing"]' },
    secondaryHighlight: { kind: 'data', selector: '[data-tutorial-data-main-tab="comparing"]' },
    action: { type: 'continue' },
  },
  {
    id: 'go-editing',
    title: 'Editing',
    description: 'Stay on Editing for this tutorial.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-main-tab="editing"]' },
    action: { type: 'data-main-tab', tab: 'editing' },
  },
  {
    id: 'go-products',
    title: 'Products',
    description: 'Go to Products. Canvas nodes will update when product data changes.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-edit-tab="products"]' },
    action: { type: 'data-edit-tab', tab: 'products' },
  },
  {
    id: 'search-coal',
    title: 'Search Coal',
    description: 'Search for Coal.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-search="product"]' },
    action: { type: 'data-search', entity: 'product', query: 'coal' },
  },
  {
    id: 'select-coal',
    title: 'Select Coal',
    description: 'Select the Coal product entry.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-row="product:p_coal"]' },
    action: { type: 'data-select', entity: 'product', id: 'p_coal' },
  },
  {
    id: 'coal-name',
    title: 'Rename Product',
    description: 'Change the product name to Coal Ingot.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.name"]' },
    action: { type: 'data-field', field: 'product.name', value: 'Coal Ingot' },
  },
  {
    id: 'coal-price',
    title: 'Sell Cost',
    description: 'Set Sell Cost to 1500.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.sell_price"]' },
    action: { type: 'data-field', field: 'product.sell_price', value: 1500 },
  },
  {
    id: 'coal-rp',
    title: 'Research Multiplier',
    description: 'Set Research Point Multiplier to 3.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.rp_multiplier"]' },
    action: { type: 'data-field', field: 'product.rp_multiplier', value: 3 },
  },
  {
    id: 'save-coal-edit',
    title: 'Save Changes',
    description: 'Save the edited product data.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-save="changes"]' },
    action: { type: 'data-save' },
  },
  {
    id: 'close-data-after-edit',
    title: 'Close Data Manager',
    description: 'Close the overlay so we can see the selector using the edited product data.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-close="true"]' },
    action: { type: 'data-close' },
  },
  {
    id: 'open-add-recipe',
    title: 'Open Add Recipe',
    description: 'Open Add Recipe.',
    highlight: { kind: 'control', id: 'add_recipe' },
    action: { type: 'control', id: 'add_recipe' },
  },
  {
    id: 'selector-search-coal',
    title: 'Search Coal',
    description:
      'Search for Coal. The entry is now Coal Ingot, and the selector reflects the edited price and RP multiplier.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-search="product"]' },
    action: { type: 'selector-search', query: 'coal' },
  },
  {
    id: 'select-coal-ingot-renamed',
    title: 'Select Coal Ingot',
    description: 'Select the renamed Coal Ingot entry.',
    highlight: { kind: 'product-row', productId: 'p_coal' },
    action: { type: 'selector-product', productId: 'p_coal' },
  },
  {
    id: 'select-coal-drill',
    title: 'Same Recipe IDs',
    description:
      'The Coal Drill recipe still appears because recipes use product IDs, not names. Select it to place the node.',
    highlight: { kind: 'recipe-card', recipeId: 'r_coal_drill_01' },
    action: { type: 'selector-recipe', recipeId: 'r_coal_drill_01', alias: 'coalDrillTutorial' },
  },
  {
    id: 'coal-node-created',
    title: 'Node Updated From Data',
    description: 'The created node is still the Coal Drill recipe, but the displayed product name follows the edited product data.',
    highlight: { kind: 'node', alias: 'coalDrillTutorial' },
    action: { type: 'continue' },
  },
  {
    id: 'reopen-data-restore',
    title: 'Restore Coal',
    description: 'Open Data Manager again so we can restore Coal back to baseline defaults.',
    highlight: { kind: 'overlay', id: 'data' },
    action: { type: 'overlay', id: 'data' },
  },
  {
    id: 'restore-editing',
    title: 'Editing',
    description: 'Go to Editing.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-main-tab="editing"]' },
    action: { type: 'data-main-tab', tab: 'editing' },
  },
  {
    id: 'restore-products',
    title: 'Products',
    description: 'Go to Products.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-edit-tab="products"]' },
    action: { type: 'data-edit-tab', tab: 'products' },
  },
  {
    id: 'search-coal-ingot',
    title: 'Find Coal Ingot',
    description: 'Search for Coal Ingot.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-search="product"]' },
    action: { type: 'data-search', entity: 'product', query: 'coal ingot' },
  },
  {
    id: 'select-edited-coal',
    title: 'Select Coal Ingot',
    description: 'Select the edited Coal Ingot entry.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-row="product:p_coal"]' },
    action: { type: 'data-select', entity: 'product', id: 'p_coal' },
  },
  {
    id: 'restore-coal',
    title: 'Restore Baseline',
    description: 'Restore this product back to baseline defaults.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-restore="product:p_coal"]' },
    action: { type: 'data-restore', entity: 'product', id: 'p_coal' },
  },
  {
    id: 'close-data-after-restore',
    title: 'Close Data Manager',
    description: 'Close the overlay and look at the existing node. Its displayed output should update back to Coal.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-close="true"]' },
    action: { type: 'data-close' },
  },
  {
    id: 'coal-node-restored',
    title: 'Canvas Refresh',
    description: 'The existing node now reflects the restored Coal data. Data edits update existing canvas nodes, not just newly created nodes.',
    highlight: { kind: 'node', alias: 'coalDrillTutorial' },
    action: { type: 'continue' },
  },
  {
    id: 'open-data-new-records',
    title: 'Create New Data',
    description: 'Open Data Manager again. This time we will add a new machine, product, and recipe.',
    highlight: { kind: 'overlay', id: 'data' },
    action: { type: 'overlay', id: 'data' },
  },
  {
    id: 'new-machine-tab',
    title: 'Machines',
    description: 'Go to Machines.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-edit-tab="machines"]' },
    action: { type: 'data-edit-tab', tab: 'machines' },
  },
  {
    id: 'add-machine',
    title: 'Add Machine',
    description: 'Add a new machine entry.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-add="machine"]' },
    action: { type: 'data-add', entity: 'machine' },
  },
  {
    id: 'machine-name',
    title: 'Machine Name',
    description: 'Set the machine name to Coal Ingot Factory.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.name"]' },
    action: { type: 'data-field', field: 'machine.name', value: 'Coal Ingot Factory' },
  },
  {
    id: 'machine-cost',
    title: 'Machine Cost',
    description: 'Set Cost to 1000000.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.cost"]' },
    action: { type: 'data-field', field: 'machine.cost', value: 1000000 },
  },
  {
    id: 'machine-tier',
    title: 'Machine Tier',
    description: 'Set Machine Tier to 3.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.tier"]' },
    action: { type: 'data-field', field: 'machine.tier', value: 3 },
  },
  {
    id: 'machine-size-x',
    title: 'Size X',
    description: 'Set Size X to 6.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.size.x"]' },
    action: { type: 'data-field', field: 'machine.size.x', value: 6 },
  },
  {
    id: 'machine-size-y',
    title: 'Size Y',
    description: 'Set Size Y to 7.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.size.y"]' },
    action: { type: 'data-field', field: 'machine.size.y', value: 7 },
  },
  {
    id: 'machine-category',
    title: 'Machine Category',
    description: 'Set Category to Factory.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.category"]' },
    action: { type: 'data-field', field: 'machine.category', value: 'Factory' },
    popoverSide: 'left',
  },
  {
    id: 'machine-subcategory',
    title: 'Machine Subcategory',
    description: 'Type furnace and select Furnace as the subcategory.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="machine.subcategory"]' },
    action: { type: 'data-field', field: 'machine.subcategory', value: 'Furnace' },
    popoverSide: 'left',
  },
  {
    id: 'save-machine',
    title: 'Save Machine',
    description: 'Save the new machine.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-save="changes"]' },
    action: { type: 'data-save' },
  },
  {
    id: 'new-product-tab',
    title: 'New Product',
    description: 'Go back to Products.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-edit-tab="products"]' },
    action: { type: 'data-edit-tab', tab: 'products' },
  },
  {
    id: 'add-product',
    title: 'Add Product',
    description: 'Add a new product entry.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-add="product"]' },
    action: { type: 'data-add', entity: 'product' },
  },
  {
    id: 'new-product-name',
    title: 'Product Name',
    description: 'Name it Coal Ingot.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.name"]' },
    action: { type: 'data-field', field: 'product.name', value: 'Coal Ingot' },
  },
  {
    id: 'new-product-price',
    title: 'Sell Cost',
    description: 'Set Sell Cost to 1500.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.sell_price"]' },
    action: { type: 'data-field', field: 'product.sell_price', value: 1500 },
  },
  {
    id: 'new-product-rp',
    title: 'Research Multiplier',
    description: 'Set Research Point Multiplier to 3.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="product.rp_multiplier"]' },
    action: { type: 'data-field', field: 'product.rp_multiplier', value: 3 },
  },
  {
    id: 'save-product',
    title: 'Save Product',
    description: 'Save the new product.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-save="changes"]' },
    action: { type: 'data-save' },
  },
  {
    id: 'new-recipe-tab',
    title: 'New Recipe',
    description: 'Go to Recipes.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-edit-tab="recipes"]' },
    action: { type: 'data-edit-tab', tab: 'recipes' },
  },
  {
    id: 'add-recipe-record',
    title: 'Add Recipe',
    description: 'Add a new recipe entry.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-add="recipe"]' },
    action: { type: 'data-add', entity: 'recipe' },
  },
  {
    id: 'recipe-name',
    title: 'Recipe Name',
    description: 'Name the recipe Makes Coal Ingot.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.name"]' },
    action: { type: 'data-field', field: 'recipe.name', value: 'Makes Coal Ingot' },
  },
  {
    id: 'recipe-machine',
    title: 'Crafted In',
    description: 'Set Crafted In to Coal Ingot Factory.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.machine_id"]' },
    action: { type: 'data-field', field: 'recipe.machine_id', value: 'm_coal_ingot_factory' },
    popoverSide: 'left',
  },
  {
    id: 'recipe-power',
    title: 'Power Consumption',
    description: 'Set Power Consumption to 8080.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.power_consumption"]' },
    action: { type: 'data-field', field: 'recipe.power_consumption', value: 8080 },
  },
  {
    id: 'recipe-cycle',
    title: 'Cycle Time',
    description: 'Set Cycle Time to 10.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.cycle_time"]' },
    action: { type: 'data-field', field: 'recipe.cycle_time', value: 10 },
  },
  {
    id: 'recipe-pollution',
    title: 'Pollution Rate',
    description: 'Set Base Pollution Rate to 0.124.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.pollution"]' },
    action: { type: 'data-field', field: 'recipe.pollution', value: 0.124 },
  },
  {
    id: 'add-input-one',
    title: 'Add Input',
    description: 'Add the first input row.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-command="recipe.add-input"]' },
    action: { type: 'data-command', id: 'recipe.add-input' },
  },
  {
    id: 'add-input-two',
    title: 'Add Another Input',
    description: 'Add the second input row.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-command="recipe.add-input"]' },
    action: { type: 'data-command', id: 'recipe.add-input' },
  },
  {
    id: 'add-output-one',
    title: 'Add Output',
    description: 'Add one output row.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-command="recipe.add-output"]' },
    action: { type: 'data-command', id: 'recipe.add-output' },
  },
  {
    id: 'recipe-input-coal',
    title: 'First Input Product',
    description: 'Set the first input product to Coal.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.input.0.product_id"]' },
    action: { type: 'data-field', field: 'recipe.input.0.product_id', value: 'p_coal' },
    popoverSide: 'left',
  },
  {
    id: 'recipe-input-cat',
    title: 'Second Input Product',
    description: 'Set the second input product to Cat.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.input.1.product_id"]' },
    action: { type: 'data-field', field: 'recipe.input.1.product_id', value: 'p_cat' },
    popoverSide: 'left',
  },
  {
    id: 'recipe-input-coal-qty',
    title: 'Coal Quantity',
    description: 'Set the Coal input quantity to 5.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.input.0.quantity"]' },
    action: { type: 'data-field', field: 'recipe.input.0.quantity', value: 5 },
  },
  {
    id: 'recipe-input-cat-qty',
    title: 'Cat Quantity',
    description: 'Set the Cat input quantity to 2.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.input.1.quantity"]' },
    action: { type: 'data-field', field: 'recipe.input.1.quantity', value: 2 },
  },
  {
    id: 'recipe-output-product',
    title: 'Output Product',
    description: 'Set the output product to Coal Ingot.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.output.0.product_id"]' },
    action: { type: 'data-field', field: 'recipe.output.0.product_id', value: 'p_coal_ingot' },
    popoverSide: 'left',
  },
  {
    id: 'recipe-output-qty',
    title: 'Output Quantity',
    description: 'Set the output quantity to 2.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-field="recipe.output.0.quantity"]' },
    action: { type: 'data-field', field: 'recipe.output.0.quantity', value: 2 },
  },
  {
    id: 'save-recipe',
    title: 'Save Recipe',
    description: 'Save the new recipe.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-save="changes"]' },
    action: { type: 'data-save' },
  },
  {
    id: 'close-data-final',
    title: 'Back To Canvas',
    description: 'Close Data Manager.',
    highlight: { kind: 'data', selector: '[data-tutorial-data-close="true"]' },
    action: { type: 'data-close' },
  },
  {
    id: 'open-selector-final',
    title: 'Use The New Recipe',
    description: 'Open Add Recipe.',
    highlight: { kind: 'control', id: 'add_recipe' },
    action: { type: 'control', id: 'add_recipe' },
  },
  {
    id: 'search-new-product',
    title: 'Search Coal Ingot',
    description: 'Search for Coal Ingot.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-search="product"]' },
    action: { type: 'selector-search', query: 'coal ingot' },
  },
  {
    id: 'select-new-product',
    title: 'Select Coal Ingot',
    description: 'Select the custom Coal Ingot product.',
    highlight: { kind: 'product-row', productId: 'p_coal_ingot' },
    action: { type: 'selector-product', productId: 'p_coal_ingot' },
  },
  {
    id: 'select-new-recipe',
    title: 'Place Custom Recipe',
    description: 'Select the new Makes Coal Ingot recipe. Tada: the app now has a custom recipe.',
    highlight: { kind: 'recipe-card', recipeId: 'r_coal_ingot_factory_01' },
    action: { type: 'selector-recipe', recipeId: 'r_coal_ingot_factory_01' },
  },
  {
    id: 'done',
    title: 'Data Tutorial Complete',
    description:
      'The tutorial data is saved as normal custom data. To remove it later, open Data Manager and restore defaults in Products, Recipes, and Machines.',
    highlight: { kind: 'overlay', id: 'data' },
    action: { type: 'continue' },
  },
];
