import type { TutorialStep } from './types';

export const FIRST_PRODUCTION_CHAIN_PROMPT_KEY =
  'industrialist_first_production_chain_prompt_v1';

export const FIRST_PRODUCTION_CHAIN_COMPLETED_KEY =
  'industrialist_first_production_chain_completed_v1';

export const FIRST_PRODUCTION_CHAIN_TUTORIAL_ID = 'first-production-chain' as const;

export const FIRST_PRODUCTION_CHAIN_SAVE_NAME = 'Gearbox Tutorial';

export const FIRST_PRODUCTION_CHAIN_RECIPE_IDS = [
  'r_craft_assembler_06',
  'r_craft_assembler_05',
  'r_roller_03',
  'r_roller_04',
  'r_press_03',
  'r_blast_furnace_02',
  'r_blast_furnace_03',
  'r_coal_drill_01',
  'r_grinder_03',
  'r_iron_drill_01',
  'r_industrial_plastic_molder_02',
  'r_plastic_production_facility_01',
  'r_plastic_refinery_02',
  'r_oxidation_plant_01',
  'r_plastic_refinery_01',
  'r_oil_rig_01',
  'r_water_pump2_01',
  'r_steam_cracking_plant_01',
  'r_oxidation_plant_02',
  'r_boiler_01',
  'r_gas_burner_01',
  'r_gas_refinery_01',
  'r_condenser_01',
  'r_natural_gas_well_01',
  'r_van_depot_01',
] as const;

export const FIRST_PRODUCTION_CHAIN_STEPS: TutorialStep[] = [
  {
    id: 'open-add-recipe',
    title: 'Start With A Gearbox',
    description: 'Open Add Recipe. The tutorial will keep the canvas focused on this chain.',
    highlight: { kind: 'control', id: 'add_recipe' },
    action: { type: 'control', id: 'add_recipe' },
  },
  {
    id: 'search-by-product',
    title: 'Search By Product',
    description: 'Choose product search so we can start from the output we want.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-tab="product"]' },
    action: { type: 'selector-tab', tab: 'product' },
  },
  {
    id: 'search-gearbox',
    title: 'Find Gearbox',
    description: 'Search for Gearbox.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-search="product"]' },
    action: { type: 'selector-search', query: 'Gearbox' },
  },
  {
    id: 'select-gearbox-product',
    title: 'Select Gearbox',
    description: 'Select Gearbox to show recipes involving that product.',
    highlight: { kind: 'product-row', productId: 'p_gearbox' },
    action: { type: 'selector-product', productId: 'p_gearbox' },
  },
  {
    id: 'disable-consumer-filter',
    title: 'Hide Consumers',
    description: 'Disable Consumer so the list only shows recipes that produce Gearbox.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter="consumer"]' },
    action: { type: 'selector-filter', filter: 'consumer', value: false },
  },
  {
    id: 'explain-recipe-card',
    title: 'Recipe Card',
    description: 'Recipe cards show the machine, inputs, outputs, cycle time, power, and pollution.',
    highlight: { kind: 'recipe-card', recipeId: 'r_craft_assembler_06' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'select-gearbox-recipe',
    title: 'Place Gearbox',
    description: 'Select the Craft Assembler Gearbox recipe.',
    highlight: { kind: 'recipe-card', recipeId: 'r_craft_assembler_06' },
    action: { type: 'selector-recipe', recipeId: 'r_craft_assembler_06', alias: 'gearbox' },
  },
  {
    id: 'explain-gearbox-node',
    title: 'Gearbox Node',
    description: 'The node shows required inputs on the left and Gearbox output on the right.',
    highlight: { kind: 'node', alias: 'gearbox' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'click-crankshaft-input',
    title: 'Add Crankshaft',
    description: 'Click the Crankshaft input to add a producer for it.',
    highlight: { kind: 'rect', alias: 'gearbox', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'gearbox', side: 'input', index: 1 },
  },
  {
    id: 'explain-crankshaft-filter',
    title: 'Filtered Producer List',
    description: 'The selector is already filtered to producers of Crankshaft.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter-row="product"]' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'select-crankshaft',
    title: 'Place Crankshaft',
    description: 'Select Craft Assembler Crankshaft.',
    highlight: { kind: 'recipe-card', recipeId: 'r_craft_assembler_05' },
    action: { type: 'selector-recipe', recipeId: 'r_craft_assembler_05', alias: 'crankshaft' },
  },
  {
    id: 'explain-auto-connect',
    title: 'Auto Connect',
    description: 'The new producer is connected to the input you clicked.',
    highlight: { kind: 'rect', alias: 'gearbox', side: 'input', index: 1 },
    secondaryHighlights: [
      { kind: 'rect', alias: 'crankshaft', side: 'output', index: 0 },
      {
        kind: 'edge',
        sourceAlias: 'crankshaft',
        sourceIndex: 0,
        targetAlias: 'gearbox',
        targetIndex: 1,
      },
    ],
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'steel-rod-input',
    title: 'Add Steel Rod',
    description: 'Click the Steel Rod input on Crankshaft.',
    highlight: { kind: 'rect', alias: 'crankshaft', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'crankshaft', side: 'input', index: 0 },
  },
  {
    id: 'select-steel-rod',
    title: 'Roll Steel Rod',
    description: 'Select Roller Steel Rod.',
    highlight: { kind: 'recipe-card', recipeId: 'r_roller_03' },
    action: { type: 'selector-recipe', recipeId: 'r_roller_03', alias: 'steelRod' },
  },
  {
    id: 'gear-input',
    title: 'Add Gear',
    description: 'Click the Gear input on Crankshaft.',
    highlight: { kind: 'rect', alias: 'crankshaft', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'crankshaft', side: 'input', index: 1 },
  },
  {
    id: 'select-gear',
    title: 'Roll Gear',
    description: 'Select Roller Gear.',
    highlight: { kind: 'recipe-card', recipeId: 'r_roller_04' },
    action: { type: 'selector-recipe', recipeId: 'r_roller_04', alias: 'gear' },
  },
  {
    id: 'steel-plate-input',
    title: 'Add Steel Plate',
    description: 'Click the Steel Plate input on Gear.',
    highlight: { kind: 'rect', alias: 'gear', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'gear', side: 'input', index: 0 },
  },
  {
    id: 'select-steel-plate',
    title: 'Press Steel Plate',
    description: 'Select Press Steel Plate.',
    highlight: { kind: 'recipe-card', recipeId: 'r_press_03' },
    action: { type: 'selector-recipe', recipeId: 'r_press_03', alias: 'steelPlate' },
  },
  {
    id: 'steel-ingot-input',
    title: 'Add Steel Ingot',
    description: 'Click Steel Rod’s Steel Ingot input.',
    highlight: { kind: 'rect', alias: 'steelRod', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'steelRod', side: 'input', index: 0 },
  },
  {
    id: 'select-steel-ingot',
    title: 'Blast Furnace Steel',
    description: 'Select Blast Furnace Steel Ingot.',
    highlight: { kind: 'recipe-card', recipeId: 'r_blast_furnace_02' },
    action: { type: 'selector-recipe', recipeId: 'r_blast_furnace_02', alias: 'steelIngot' },
  },
  {
    id: 'connect-steel-ingot-to-steel-plate',
    title: 'Connect Steel To Plate',
    description: 'Connect the Blast Furnace Steel Ingot output to the Press Steel Plate input.',
    highlight: { kind: 'handle', alias: 'steelIngot', side: 'output', index: 0 },
    secondaryHighlight: { kind: 'handle', alias: 'steelPlate', side: 'input', index: 0 },
    action: {
      type: 'edge-connect',
      sourceAlias: 'steelIngot',
      sourceIndex: 0,
      targetAlias: 'steelPlate',
      targetIndex: 0,
    },
  },
  {
    id: 'balance-steel-ingot-output',
    title: 'Double-Click To Balance',
    description: 'Double-click the Steel Ingot output to balance connected Steel demand.',
    highlight: { kind: 'handle', alias: 'steelIngot', side: 'output', index: 0 },
    action: { type: 'node-handle-double', alias: 'steelIngot', side: 'output', index: 0 },
  },
  {
    id: 'iron-mix-input',
    title: 'Add Iron Mix',
    description: 'Click the Iron Mix input on the Steel Ingot Blast Furnace.',
    highlight: { kind: 'rect', alias: 'steelIngot', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'steelIngot', side: 'input', index: 1 },
  },
  {
    id: 'select-iron-mix',
    title: 'Blast Furnace Iron Mix',
    description: 'Select Blast Furnace Iron Mix.',
    highlight: { kind: 'recipe-card', recipeId: 'r_blast_furnace_03' },
    action: { type: 'selector-recipe', recipeId: 'r_blast_furnace_03', alias: 'ironMix' },
  },
  {
    id: 'coal-input-iron-mix',
    title: 'Add Coal',
    description: 'Click Coal input on the Iron Mix Blast Furnace.',
    highlight: { kind: 'rect', alias: 'ironMix', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'ironMix', side: 'input', index: 0 },
  },
  {
    id: 'select-coal-drill',
    title: 'Coal Drill',
    description: 'Select Coal Drill.',
    highlight: { kind: 'recipe-card', recipeId: 'r_coal_drill_01' },
    action: { type: 'selector-recipe', recipeId: 'r_coal_drill_01', alias: 'coalForIronMix' },
  },
  {
    id: 'connect-coal-to-steel',
    title: 'Share Coal',
    description: 'Connect Coal Drill output to the Coal input on Steel Ingot Blast Furnace.',
    highlight: { kind: 'handle', alias: 'coalForIronMix', side: 'output', index: 0 },
    secondaryHighlight: { kind: 'handle', alias: 'steelIngot', side: 'input', index: 0 },
    action: {
      type: 'edge-connect',
      sourceAlias: 'coalForIronMix',
      sourceIndex: 0,
      targetAlias: 'steelIngot',
      targetIndex: 0,
    },
  },
  {
    id: 'balance-coal',
    title: 'Balance Coal',
    description: 'Double-click the Coal Drill output.',
    highlight: { kind: 'handle', alias: 'coalForIronMix', side: 'output', index: 0 },
    action: { type: 'node-handle-double', alias: 'coalForIronMix', side: 'output', index: 0 },
  },
  {
    id: 'iron-powder-input',
    title: 'Add Iron Powder',
    description: 'Click Iron Powder input on Iron Mix Blast Furnace.',
    highlight: { kind: 'rect', alias: 'ironMix', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'ironMix', side: 'input', index: 1 },
  },
  {
    id: 'select-iron-powder',
    title: 'Grind Raw Iron',
    description: 'Select Grinder Raw Iron to Iron Powder.',
    highlight: { kind: 'recipe-card', recipeId: 'r_grinder_03' },
    action: { type: 'selector-recipe', recipeId: 'r_grinder_03', alias: 'ironPowder' },
  },
  {
    id: 'raw-iron-input',
    title: 'Add Raw Iron',
    description: 'Click Raw Iron input on the Grinder.',
    highlight: { kind: 'rect', alias: 'ironPowder', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'ironPowder', side: 'input', index: 0 },
  },
  {
    id: 'select-iron-drill',
    title: 'Iron Drill',
    description: 'Select Iron Drill.',
    highlight: { kind: 'recipe-card', recipeId: 'r_iron_drill_01' },
    action: { type: 'selector-recipe', recipeId: 'r_iron_drill_01', alias: 'rawIron' },
  },
  {
    id: 'crankshaft-branch-done',
    title: 'Crankshaft Branch Done',
    description: 'The Crankshaft branch is connected. Plastic Casing still needs work.',
    highlight: { kind: 'node', alias: 'crankshaft' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'show-plastic-deficient',
    title: 'Dashboard Shortage',
    description: 'The Dashboard shows Plastic Casing is still deficient.',
    highlight: { kind: 'diagnostic', status: 'deficiency', productId: 'p_plastic_casing' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'expand-plastic-deficiency',
    title: 'Open Plastic Shortage',
    description: 'Click the Plastic Casing deficiency row.',
    highlight: { kind: 'diagnostic', status: 'deficiency', productId: 'p_plastic_casing' },
    action: { type: 'dashboard-diagnostic', status: 'deficiency', productId: 'p_plastic_casing' },
  },
  {
    id: 'center-gearbox-from-plastic',
    title: 'Center Gearbox',
    description: 'Select the Craft Assembler entry to center on Gearbox.',
    highlight: {
      kind: 'diagnostic',
      status: 'deficiency',
      productId: 'p_plastic_casing',
      nodeAlias: 'gearbox',
    },
    action: {
      type: 'dashboard-diagnostic',
      status: 'deficiency',
      productId: 'p_plastic_casing',
      nodeAlias: 'gearbox',
    },
  },
  {
    id: 'plastic-casing-input',
    title: 'Add Plastic Casing',
    description: 'Click the Plastic Casing input.',
    highlight: { kind: 'rect', alias: 'gearbox', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'gearbox', side: 'input', index: 0 },
  },
  {
    id: 'select-plastic-casing',
    title: 'Mold Plastic Casing',
    description: 'Select Industrial Plastic Molder Plastic Casing.',
    highlight: { kind: 'recipe-card', recipeId: 'r_industrial_plastic_molder_02' },
    action: {
      type: 'selector-recipe',
      recipeId: 'r_industrial_plastic_molder_02',
      alias: 'plasticCasing',
    },
  },
  {
    id: 'plastic-pellets-input',
    title: 'Add Plastic Pellets',
    description: 'Click the Plastic Pellets input.',
    highlight: { kind: 'rect', alias: 'plasticCasing', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'plasticCasing', side: 'input', index: 0 },
  },
  {
    id: 'select-plastic-pellets',
    title: 'Plastic Pellets',
    description: 'Select Plastic Production Facility Plastic Pellets.',
    highlight: { kind: 'recipe-card', recipeId: 'r_plastic_production_facility_01' },
    action: {
      type: 'selector-recipe',
      recipeId: 'r_plastic_production_facility_01',
      alias: 'plasticPellets',
    },
  },
  {
    id: 'pta-input',
    title: 'Add PTA',
    description: 'Click the PTA input.',
    highlight: { kind: 'rect', alias: 'plasticPellets', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'plasticPellets', side: 'input', index: 1 },
  },
  {
    id: 'select-pta',
    title: 'Refine PTA',
    description: 'Select Plastic Refinery PTA.',
    highlight: { kind: 'recipe-card', recipeId: 'r_plastic_refinery_02' },
    action: { type: 'selector-recipe', recipeId: 'r_plastic_refinery_02', alias: 'pta' },
  },
  {
    id: 'acetic-acid-input',
    title: 'Add Acetic Acid',
    description: 'Click the Acetic Acid input.',
    highlight: { kind: 'rect', alias: 'pta', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'pta', side: 'input', index: 1 },
  },
  {
    id: 'select-acetic-acid',
    title: 'Acetic Acid',
    description: 'Select Oxidation Plant Acetic Acid without oxygen.',
    highlight: { kind: 'recipe-card', recipeId: 'r_oxidation_plant_01' },
    action: { type: 'selector-recipe', recipeId: 'r_oxidation_plant_01', alias: 'aceticAcid' },
  },
  {
    id: 'ethanol-input',
    title: 'Add Ethanol',
    description: 'Click the Ethanol input.',
    highlight: { kind: 'rect', alias: 'aceticAcid', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'aceticAcid', side: 'input', index: 0 },
  },
  {
    id: 'select-ethanol',
    title: 'Refine Ethanol',
    description: 'Select Plastic Refinery Ethanol.',
    highlight: { kind: 'recipe-card', recipeId: 'r_plastic_refinery_01' },
    action: { type: 'selector-recipe', recipeId: 'r_plastic_refinery_01', alias: 'ethanol' },
  },
  {
    id: 'crude-oil-ethanol-input',
    title: 'Add Crude Oil',
    description: 'Click the Crude Oil input.',
    highlight: { kind: 'rect', alias: 'ethanol', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'ethanol', side: 'input', index: 0 },
  },
  {
    id: 'select-oil-rig-ethanol',
    title: 'Oil Rig',
    description: 'Select Oil Rig.',
    highlight: { kind: 'recipe-card', recipeId: 'r_oil_rig_01' },
    action: { type: 'selector-recipe', recipeId: 'r_oil_rig_01', alias: 'crudeOilForEthanol' },
  },
  {
    id: 'water-ethanol-input',
    title: 'Add Water',
    description: 'Click the Water input.',
    highlight: { kind: 'rect', alias: 'ethanol', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'ethanol', side: 'input', index: 1 },
  },
  {
    id: 'select-water-pump-ethanol',
    title: 'Water Pump 2',
    description: 'Select Water Pump 2.',
    highlight: { kind: 'recipe-card', recipeId: 'r_water_pump2_01' },
    action: { type: 'selector-recipe', recipeId: 'r_water_pump2_01', alias: 'waterForEthanol' },
  },
  {
    id: 'expand-paraxylene-deficiency',
    title: 'Paraxylene Shortage',
    description: 'Select the Paraxylene deficiency in the Dashboard.',
    highlight: { kind: 'diagnostic', status: 'deficiency', productId: 'p_paraxylene' },
    action: { type: 'dashboard-diagnostic', status: 'deficiency', productId: 'p_paraxylene' },
  },
  {
    id: 'center-pta-from-paraxylene',
    title: 'Center PTA Refinery',
    description: 'Center on the Plastic Refinery needing Paraxylene.',
    highlight: {
      kind: 'diagnostic',
      status: 'deficiency',
      productId: 'p_paraxylene',
      nodeAlias: 'pta',
    },
    action: {
      type: 'dashboard-diagnostic',
      status: 'deficiency',
      productId: 'p_paraxylene',
      nodeAlias: 'pta',
    },
  },
  {
    id: 'paraxylene-input',
    title: 'Add Paraxylene',
    description: 'Click the Paraxylene input.',
    highlight: { kind: 'rect', alias: 'pta', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'pta', side: 'input', index: 0 },
  },
  {
    id: 'select-steam-cracker',
    title: 'Steam Cracking',
    description: 'Select Steam Cracking Plant Paraxylene/Ethylene.',
    highlight: { kind: 'recipe-card', recipeId: 'r_steam_cracking_plant_01' },
    action: {
      type: 'selector-recipe',
      recipeId: 'r_steam_cracking_plant_01',
      alias: 'steamCracker',
    },
  },
  {
    id: 'open-steam-cracker-editor',
    title: 'Open Node Editor',
    description: 'Open the Steam Cracking Plant node editor.',
    highlight: { kind: 'node-editor-button', alias: 'steamCracker' },
    action: { type: 'node-editor-open', alias: 'steamCracker' },
  },
  {
    id: 'settings-tab',
    title: 'Settings',
    description: 'Go to Settings.',
    highlight: { kind: 'node-editor', id: 'settings-tab' },
    action: { type: 'node-editor-tab', tab: 'settings' },
  },
  {
    id: 'review-steam-temp',
    title: 'Steam Temperature',
    description: 'Review Steam Temperature. Connected steam edges override this value later.',
    highlight: { kind: 'node-editor', id: 'setting-steam_temp' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'apply-steam-temp',
    title: 'Apply Settings',
    description: 'Leave Steam Temperature at 400 and Apply.',
    highlight: { kind: 'node-editor', id: 'apply-local' },
    action: { type: 'node-editor-apply', mode: 'local' },
  },
  {
    id: 'ethylene-output',
    title: 'Ethylene Consumers',
    description: 'Click the Ethylene output. The selector will show consumers of Ethylene.',
    highlight: { kind: 'rect', alias: 'steamCracker', side: 'output', index: 1 },
    action: { type: 'node-rect', alias: 'steamCracker', side: 'output', index: 1 },
  },
  {
    id: 'select-meg',
    title: 'Make MEG',
    description: 'Select Oxidation Plant Ethylene to MEG.',
    highlight: { kind: 'recipe-card', recipeId: 'r_oxidation_plant_02' },
    action: { type: 'selector-recipe', recipeId: 'r_oxidation_plant_02', alias: 'meg' },
  },
  {
    id: 'connect-meg',
    title: 'Connect MEG',
    description: 'Connect MEG output to Plastic Production Facility MEG input.',
    highlight: { kind: 'handle', alias: 'meg', side: 'output', index: 0 },
    secondaryHighlight: { kind: 'handle', alias: 'plasticPellets', side: 'input', index: 0 },
    action: {
      type: 'edge-connect',
      sourceAlias: 'meg',
      sourceIndex: 0,
      targetAlias: 'plasticPellets',
      targetIndex: 0,
    },
  },
  {
    id: 'show-meg-insufficient',
    title: 'MEG Is Short',
    description: 'The Dashboard shows the MEG rate is insufficient.',
    highlight: { kind: 'diagnostic', status: 'deficiency', productId: 'p_meg' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'balance-meg-output',
    title: 'Balance MEG',
    description: 'Double-click MEG output to match the requirement.',
    highlight: { kind: 'handle', alias: 'meg', side: 'output', index: 0 },
    action: { type: 'node-handle-double', alias: 'meg', side: 'output', index: 0 },
  },
  {
    id: 'balance-ethylene-output',
    title: 'Balance Ethylene',
    description: 'Double-click Steam Cracking Plant Ethylene output to match MEG demand.',
    highlight: { kind: 'handle', alias: 'steamCracker', side: 'output', index: 1 },
    action: { type: 'node-handle-double', alias: 'steamCracker', side: 'output', index: 1 },
  },
  {
    id: 'paraxylene-excess',
    title: 'Paraxylene Excess',
    description: 'Paraxylene is now excess because Ethylene demand raised Steam Cracking output.',
    highlight: { kind: 'diagnostic', status: 'excess', productId: 'p_paraxylene' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'steam-cracker-crude-input',
    title: 'Crude Oil For Cracker',
    description: 'Click Crude Oil input on the Steam Cracking Plant.',
    highlight: { kind: 'rect', alias: 'steamCracker', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'steamCracker', side: 'input', index: 0 },
  },
  {
    id: 'select-oil-rig-cracker',
    title: 'New Oil Rig',
    description: 'Get Crude Oil from a new Oil Rig recipe.',
    highlight: { kind: 'recipe-card', recipeId: 'r_oil_rig_01' },
    action: {
      type: 'selector-recipe',
      recipeId: 'r_oil_rig_01',
      alias: 'crudeOilForSteamCracker',
    },
  },
  {
    id: 'steam-input',
    title: 'Add Steam',
    description: 'Click the Steam input on the Steam Cracking Plant.',
    highlight: { kind: 'rect', alias: 'steamCracker', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'steamCracker', side: 'input', index: 1 },
  },
  {
    id: 'select-boiler',
    title: 'Boiler',
    description: 'Select Boiler for Steam.',
    highlight: { kind: 'recipe-card', recipeId: 'r_boiler_01' },
    action: { type: 'selector-recipe', recipeId: 'r_boiler_01', alias: 'boiler' },
  },
  {
    id: 'explain-boiler',
    title: 'Boiler Loop',
    description: 'The Boiler has water, coolant, and steam paths. First connect its coolant loop.',
    highlight: { kind: 'node', alias: 'boiler' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'connect-boiler-loop',
    title: 'Connect Coolant Loop',
    description: 'Connect Boiler any-fluid output to its any-fluid input.',
    highlight: { kind: 'handle', alias: 'boiler', side: 'output', index: 0 },
    secondaryHighlight: { kind: 'handle', alias: 'boiler', side: 'input', index: 1 },
    action: {
      type: 'edge-connect',
      sourceAlias: 'boiler',
      sourceIndex: 0,
      targetAlias: 'boiler',
      targetIndex: 1,
    },
  },
  {
    id: 'steam-zero',
    title: 'Steam Is Still Zero',
    description: 'Steam remains 0 because the Boiler temperature is not high enough yet.',
    highlight: { kind: 'rect', alias: 'boiler', side: 'output', index: 1 },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'boiler-water-input',
    title: 'Heat The Water',
    description: 'Click Boiler Water input. It needs a recipe that heats water.',
    highlight: { kind: 'rect', alias: 'boiler', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'boiler', side: 'input', index: 0 },
  },
  {
    id: 'enable-heat-filter',
    title: 'Power And Heat',
    description: 'Enable Power & Heat.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter="heatPower"]' },
    action: { type: 'selector-filter', filter: 'heatPower', value: true },
  },
  {
    id: 'disable-producer-filter',
    title: 'Disable Producer',
    description: 'Disable Producer so the heat recipe is easier to find.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter="producer"]' },
    action: { type: 'selector-filter', filter: 'producer', value: false },
  },
  {
    id: 'select-gas-burner',
    title: 'Gas Burner',
    description: 'Select Gas Burner for Refined Gas and Water.',
    highlight: { kind: 'recipe-card', recipeId: 'r_gas_burner_01' },
    action: { type: 'selector-recipe', recipeId: 'r_gas_burner_01', alias: 'gasBurner' },
  },
  {
    id: 'boiler-heat-change',
    title: 'Boiler Heat Changed',
    description: 'The Boiler heat changes to about 398.99, enough to make steam.',
    highlight: { kind: 'node', alias: 'boiler' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'steam-cracker-output-change',
    title: 'Steam Temperature Drives Output',
    description: 'The Steam Cracking Plant output changes with connected steam temperature.',
    highlight: { kind: 'node', alias: 'steamCracker' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'gas-burner-water',
    title: 'Water For Gas Burner',
    description: 'Click Gas Burner Water input.',
    highlight: { kind: 'rect', alias: 'gasBurner', side: 'input', index: 1 },
    action: { type: 'node-rect', alias: 'gasBurner', side: 'input', index: 1 },
  },
  {
    id: 'select-water-pump-burner',
    title: 'Water Pump 2',
    description: 'Get Water from Water Pump 2.',
    highlight: { kind: 'recipe-card', recipeId: 'r_water_pump2_01' },
    action: { type: 'selector-recipe', recipeId: 'r_water_pump2_01', alias: 'waterForGasBurner' },
  },
  {
    id: 'gas-burner-refined-gas',
    title: 'Refined Gas',
    description: 'Click Gas Burner Refined Gas input.',
    highlight: { kind: 'rect', alias: 'gasBurner', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'gasBurner', side: 'input', index: 0 },
  },
  {
    id: 'select-gas-refinery',
    title: 'Gas Refinery',
    description: 'Get Refined Gas from Gas Refinery.',
    highlight: { kind: 'recipe-card', recipeId: 'r_gas_refinery_01' },
    action: { type: 'selector-recipe', recipeId: 'r_gas_refinery_01', alias: 'gasRefinery' },
  },
  {
    id: 'water-free-gas-input',
    title: 'Water-Free Gas',
    description: 'Click Gas Refinery Water-Free Gas input.',
    highlight: { kind: 'rect', alias: 'gasRefinery', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'gasRefinery', side: 'input', index: 0 },
  },
  {
    id: 'select-condenser',
    title: 'Condenser',
    description: 'Get Water-Free Gas from Condenser.',
    highlight: { kind: 'recipe-card', recipeId: 'r_condenser_01' },
    action: { type: 'selector-recipe', recipeId: 'r_condenser_01', alias: 'condenser' },
  },
  {
    id: 'raw-gas-input',
    title: 'Raw Gas',
    description: 'Click Condenser Raw Gas input.',
    highlight: { kind: 'rect', alias: 'condenser', side: 'input', index: 0 },
    action: { type: 'node-rect', alias: 'condenser', side: 'input', index: 0 },
  },
  {
    id: 'select-natural-gas',
    title: 'Natural Gas Well',
    description: 'Get Raw Gas from Natural Gas Well.',
    highlight: { kind: 'recipe-card', recipeId: 'r_natural_gas_well_01' },
    action: { type: 'selector-recipe', recipeId: 'r_natural_gas_well_01', alias: 'naturalGas' },
  },
  {
    id: 'chain-complete',
    title: 'Chain Complete',
    description: 'The chain is complete, but excesses may remain.',
    highlight: { kind: 'node', alias: 'gearbox' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'expand-gearbox-excess',
    title: 'Gearbox Excess',
    description: 'Select Gearbox excess in the Dashboard.',
    highlight: { kind: 'diagnostic', status: 'excess', productId: 'p_gearbox' },
    action: { type: 'dashboard-diagnostic', status: 'excess', productId: 'p_gearbox' },
  },
  {
    id: 'center-gearbox-excess',
    title: 'Go To Gearbox',
    description: 'Go to the Craft Assembler Gearbox node.',
    highlight: {
      kind: 'diagnostic',
      status: 'excess',
      productId: 'p_gearbox',
      nodeAlias: 'gearbox',
    },
    action: {
      type: 'dashboard-diagnostic',
      status: 'excess',
      productId: 'p_gearbox',
      nodeAlias: 'gearbox',
    },
  },
  {
    id: 'enable-target-tool',
    title: 'Enable Target Tool',
    description: 'Enable the Target tool in the controls tray.',
    highlight: { kind: 'control', id: 'target' },
    action: { type: 'control', id: 'target' },
  },
  {
    id: 'set-gearbox-target',
    title: 'Set Gearbox Target',
    description: 'Click the Craft Assembler Gearbox node to mark it as the target.',
    highlight: { kind: 'node', alias: 'gearbox' },
    action: { type: 'target-node', alias: 'gearbox' },
  },
  {
    id: 'open-gearbox-editor',
    title: 'Open Gearbox Editor',
    description: 'Open the Gearbox Node Editor.',
    highlight: { kind: 'node-editor-button', alias: 'gearbox' },
    action: { type: 'node-editor-open', alias: 'gearbox' },
  },
  {
    id: 'set-gearbox-15',
    title: 'Set Count To 15',
    description: 'Set Gearbox machine count to 15.',
    highlight: { kind: 'node-editor', id: 'machine-count' },
    action: { type: 'node-editor-machine-count', alias: 'gearbox', value: 15 },
  },
  {
    id: 'apply-gearbox-15',
    title: 'Apply Count',
    description: 'Click Apply.',
    highlight: { kind: 'node-editor', id: 'apply-local' },
    action: { type: 'node-editor-apply', mode: 'local' },
  },
  {
    id: 'press-compute',
    title: 'Compute',
    description: 'Press Compute.',
    highlight: { kind: 'control', id: 'compute' },
    action: { type: 'control', id: 'compute' },
  },
  {
    id: 'wait-solver',
    title: 'Wait For Solver',
    description: 'Wait for the solver to finish.',
    highlight: { kind: 'solver', id: 'modal' },
    action: { type: 'solver-results' },
    disableActiveInteraction: true,
  },
  {
    id: 'apply-solver',
    title: 'Apply Solver',
    description: 'Apply the solver solution.',
    highlight: { kind: 'solver', id: 'apply' },
    action: { type: 'solver-apply' },
  },
  {
    id: 'open-gearbox-editor-again',
    title: 'Open Gearbox Again',
    description: 'Open Gearbox Node Editor again.',
    highlight: { kind: 'node-editor-button', alias: 'gearbox' },
    action: { type: 'node-editor-open', alias: 'gearbox' },
  },
  {
    id: 'set-gearbox-30',
    title: 'Scale To 30',
    description: 'Set Gearbox machine count to 30.',
    highlight: { kind: 'node-editor', id: 'machine-count' },
    action: { type: 'node-editor-machine-count', alias: 'gearbox', value: 30 },
  },
  {
    id: 'apply-to-chain',
    title: 'Apply To Chain',
    description: 'Click Apply to Chain to scale connected machines.',
    highlight: { kind: 'node-editor', id: 'apply-chain' },
    action: { type: 'node-editor-apply', mode: 'chain' },
  },
  {
    id: 'explain-chain-scale',
    title: 'Connected Chain Scaled',
    description: 'Apply to Chain scales connected nodes by the same ratio.',
    highlight: { kind: 'node', alias: 'gearbox' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'gearbox-output',
    title: 'Sell Gearbox',
    description: 'Click the Gearbox output.',
    highlight: { kind: 'rect', alias: 'gearbox', side: 'output', index: 0 },
    action: { type: 'node-rect', alias: 'gearbox', side: 'output', index: 0 },
  },
  {
    id: 'disable-consumer-output',
    title: 'Hide Consumers',
    description: 'Disable Consumer.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter="consumer"]' },
    action: { type: 'selector-filter', filter: 'consumer', value: false },
  },
  {
    id: 'enable-outlet-filter',
    title: 'Show Outlets',
    description: 'Enable Outlet.',
    highlight: { kind: 'selector', selector: '[data-tutorial-selector-filter="outlet"]' },
    action: { type: 'selector-filter', filter: 'outlet', value: true },
  },
  {
    id: 'select-van-depot',
    title: 'Van Depot',
    description: 'Select Van Depot.',
    highlight: { kind: 'recipe-card', recipeId: 'r_van_depot_01' },
    action: { type: 'selector-recipe', recipeId: 'r_van_depot_01', alias: 'vanDepot' },
  },
  {
    id: 'byproduct-note',
    title: 'Other Outlets',
    description:
      'Other byproducts can go to liquid dump, liquid burner, research stations, satellite dish controllers, and depots.',
    highlight: { kind: 'node', alias: 'vanDepot' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'dashboard-outputs',
    title: 'Dashboard Outputs',
    description: 'Review Dashboard outputs and remaining excesses.',
    highlight: { kind: 'dashboard', id: 'outputs' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
  {
    id: 'layout',
    title: 'Layout',
    description: 'Press Layout to organize the canvas.',
    highlight: { kind: 'control', id: 'layout' },
    action: { type: 'control', id: 'layout' },
  },
  {
    id: 'open-saves',
    title: 'Save Manager',
    description: 'Open Save Manager.',
    highlight: { kind: 'overlay', id: 'saves' },
    action: { type: 'overlay', id: 'saves' },
  },
  {
    id: 'save-name',
    title: 'Name The Save',
    description: `Set the save name to "${FIRST_PRODUCTION_CHAIN_SAVE_NAME}".`,
    highlight: { kind: 'save', id: 'name' },
    action: { type: 'save-name', value: FIRST_PRODUCTION_CHAIN_SAVE_NAME },
  },
  {
    id: 'save-create',
    title: 'Save',
    description: 'Click Save.',
    highlight: { kind: 'save', id: 'create' },
    action: { type: 'save-create', source: 'button' },
  },
  {
    id: 'finished',
    title: 'Tutorial Complete',
    description: 'Your first production chain is saved and ready to explore.',
    highlight: { kind: 'save', id: 'create' },
    action: { type: 'continue' },
    disableActiveInteraction: true,
  },
];
